sonar.projectKey=Linq
sonar.working.directory=/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/.sonarqube/out/.sonar
sonar.projectBaseDir=/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq
sonar.pullrequest.cache.basepath=/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq

2BDD7CF8-484E-44AD-9B6B-5AADFCE4A95F.sonar.projectKey=Linq:2BDD7CF8-484E-44AD-9B6B-5AADFCE4A95F
2BDD7CF8-484E-44AD-9B6B-5AADFCE4A95F.sonar.projectName=Linq
2BDD7CF8-484E-44AD-9B6B-5AADFCE4A95F.sonar.projectBaseDir=/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq
2BDD7CF8-484E-44AD-9B6B-5AADFCE4A95F.sonar.sourceEncoding=utf-8
2BDD7CF8-484E-44AD-9B6B-5AADFCE4A95F.sonar.tests=
2BDD7CF8-484E-44AD-9B6B-5AADFCE4A95F.sonar.sources=\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/AttendanceRecord.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/AttendanceService.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/Contractor.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/CustomException.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/Employee.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/FullTimeEmployee.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/IPayable.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/Migrations/20260813051713_InitialCreate.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/Migrations/20260813051713_InitialCreate.Designer.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/Migrations/PayrollDbContextModelSnapshot.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/PayrollDbContext.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/Program.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/obj/Debug/net10.0/apphost",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/obj/Linq.csproj.nuget.dgspec.json",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/obj/project.packagespec.json",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/obj/project.assets.json",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/obj/Debug/net10.0/Linq.sourcelink.json",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/bin/Debug/net10.0/Linq.runtimeconfig.json",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/bin/Debug/net10.0/Linq.deps.json"

2BDD7CF8-484E-44AD-9B6B-5AADFCE4A95F.sonar.cs.analyzer.projectOutPaths=\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/.sonarqube/out/0"
2BDD7CF8-484E-44AD-9B6B-5AADFCE4A95F.sonar.cs.roslyn.reportFilePaths=\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/.sonarqube/out/0/Issues.json"
2BDD7CF8-484E-44AD-9B6B-5AADFCE4A95F.sonar.cs.scanner.telemetry=\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/.sonarqube/out/0/Telemetry.json"

2BDD7CF8-484E-44AD-9B6B-5AADFCE4A95F.sonar.working.directory=/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/.sonarqube/out/.sonar/mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=2BDD7CF8-484E-44AD-9B6B-5AADFCE4A95F

