sonar.projectKey=Linq
sonar.working.directory=/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/.sonarqube/out/.sonar
sonar.projectBaseDir=/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq
sonar.pullrequest.cache.basepath=/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq

875769E2-57D0-4D4D-91C2-74E17DF1A4D4.sonar.projectKey=Linq:875769E2-57D0-4D4D-91C2-74E17DF1A4D4
875769E2-57D0-4D4D-91C2-74E17DF1A4D4.sonar.projectName=Linq
875769E2-57D0-4D4D-91C2-74E17DF1A4D4.sonar.projectBaseDir=/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq
875769E2-57D0-4D4D-91C2-74E17DF1A4D4.sonar.sourceEncoding=utf-8
875769E2-57D0-4D4D-91C2-74E17DF1A4D4.sonar.tests=
875769E2-57D0-4D4D-91C2-74E17DF1A4D4.sonar.sources=\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/AttendanceRecord.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/AttendanceService.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/Contractor.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/CustomException.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/Employee.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/FullTimeEmployee.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/IPayable.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/Migrations/20260813051713_InitialCreate.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/Migrations/20260813051713_InitialCreate.Designer.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/Migrations/PayrollDbContextModelSnapshot.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/PayrollDbContext.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/Program.cs",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/obj/Linq.csproj.nuget.dgspec.json",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/obj/project.packagespec.json",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/obj/project.assets.json",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/obj/Debug/net10.0/Linq.sourcelink.json",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/bin/Debug/net10.0/Linq.runtimeconfig.json",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/bin/Debug/net10.0/Linq.deps.json",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/bin/Debug/net10.0/BuildHost-net472/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/bin/Debug/net10.0/BuildHost-netcore/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json",\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/bin/Debug/net10.0/BuildHost-netcore/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json"

875769E2-57D0-4D4D-91C2-74E17DF1A4D4.sonar.cs.analyzer.projectOutPaths=\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/.sonarqube/out/0"
875769E2-57D0-4D4D-91C2-74E17DF1A4D4.sonar.cs.roslyn.reportFilePaths=\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/.sonarqube/out/0/Issues.json"
875769E2-57D0-4D4D-91C2-74E17DF1A4D4.sonar.cs.scanner.telemetry=\
"/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/.sonarqube/out/0/Telemetry.json"

875769E2-57D0-4D4D-91C2-74E17DF1A4D4.sonar.working.directory=/Users/apple/Desktop/bridge labs /ConsoleApp1/Linq/.sonarqube/out/.sonar/mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=875769E2-57D0-4D4D-91C2-74E17DF1A4D4

